name: Cyaneum NCM Auto-Deployment

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Cek kode repository & Tarik pembaruan terbaru
        run: |
          cd /opt/NCM-Network-Configuration-Management-
          git fetch origin dev
          git reset --hard origin/dev
          git pull origin dev

      - name: Instal Dependensi Backend & Build Frontend
        run: |
          cd /opt/NCM-Network-Configuration-Management-
          source venv/bin/activate
          pip install -r requirements.txt
          cd frontend
          npm install
          npm run build

      - name: Restart Layanan FastAPI & Celery Worker
        run: |
          sudo systemctl restart cyaneum-api.service
          sudo systemctl restart cyaneum-celery.service
          echo "Deployment otomatis ke server berhasil!"
